// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
}

declare namespace NodeJS {
    interface ProcessEnv {
      DATABASE_URL: string,
      DIRECT_URL: string
    }
  }
